[workspace]
resolver = "2"
members = [
    "optionize", "optionize-macros"
]

[workspace.package]
repository = "https://github.com/ZnqbuZ/optionize"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
keywords = ["builder", "config", "partial", "macro", "derive"]
categories = ["config", "rust-patterns"]

[profile.dev]
panic = "unwind"
debug = 2

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3
strip = true