[package]
name = "optionize"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "A procedural macro to generate optionized versions of structs for partial configurations, updates, and builders"
readme = "README.md"

[lib]

[dependencies]
optionize-macros = { workspace = true }
derive_more = { version = "2.1.1", features = ["full"] }