[package]
name = "optionize"
repository.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]

[dependencies]
optionize-macros = { version = "0.1", path = "../optionize-macros" }
delegate = "0.13.5"
derive_more = {version = "2.1.1", features = ["full"]}
